### ISSUE TITLE
Code Review untuk Rizki Andaru

### ISSUE THREAD

**Issue by hedydevcenter** [Rizki-Andaru/Task-UAS-Algoritma-The-micro-Sistem-management-toko-agent-sembako-podomoro#4]
## Pertanyaan Review
1. Pada fungsi `ubahHarga()`, jelaskan mengapa tidak ada validasi untuk harga baru yang dimasukkan?
2. Bagaimana jika user memasukkan input berupa huruf saat diminta memasukkan angka (misalnya saat input jumlah stok)?
3. Program belum memiliki fungsi untuk mencari produk. Bagaimana implementasi fungsi pencarian produk berdasarkan nama?
4. Bagaimana jika ingin menambahkan fitur untuk mengekspor laporan penjualan ke format teks tertentu?

## Cara Menjawab
1. Reply pada thread issue GitHub ini
2. Jelaskan setiap poin pertanyaan
3. Sebutkan file yang dimodifikasi/ditambahkan
4. Sertakan kode yang berubah/ditambahkan

**Comment by Rizki-Andaru** [comment]
> 1. jelaskan mengapa tidak ada validasi untuk harga baru yang dimasukkan?

Karena program ini dirancang sebagai prototipe awal atau dalam tahap pengembangan dasar, sehingga fungsi-fungsi yang lebih kompleks, seperti validasi input, belum menjadi prioritas. Fokus awalnya adalah memastikan alur kerja dasar seperti perubahan harga dapat berjalan.

> 2. Bagaimana jika user memasukkan input berupa huruf saat diminta memasukkan angka (misalnya saat input jumlah stok)?

maka fungsi "cin" tidak dapat memproses input tersebut sebagai angka. yang menyebabkan program mengalami kesalahan pembacaan input dan status error pada cin akan aktif. Akibatnya, input yang dimasukkan tidak akan tersimpan ke dalam variabel yang seharusnya diisi dengan angka, dan program akan gagal melanjutkan.

> 3. Program belum memiliki fungsi untuk mencari produk. Bagaimana implementasi fungsi pencarian produk berdasarkan nama?

Untuk membuat fungsi pencarian produk berdasarkan nama, program bisa meminta pengguna memasukkan nama produk yang ingin dicari. Selanjutnya, pencarian dilakukan dengan memeriksa apakah nama produk tersebut terdapat dalam daftar, menggunakan metode pencocokan substring. Jika produk ditemukan, informasi seperti nomor, nama, dan harga akan ditampilkan. Sebaliknya, jika tidak ditemukan, program akan memberikan pemberitahuan bahwa produk tidak ada. Agar lebih fleksibel, input nama produk dapat dibaca menggunakan getline() sehingga mendukung nama dengan spasi. Selain itu, cin.ignore() dapat digunakan untuk menangani karakter newline yang mungkin mengganggu. Untuk meningkatkan akurasi, pencarian bisa dibuat case-insensitive dengan mengonversi input dan nama produk ke huruf kecil sebelum dibandingkan.

> 4.Bagaimana jika ingin menambahkan fitur untuk mengekspor laporan penjualan ke format teks tertentu?

Fitur untuk mengekspor laporan penjualan ke file teks bisa dibuat dengan memanfaatkan fungsi file I/O di C++. Data produk, seperti nama, harga, jumlah terjual, dan total penjualan, ditulis ke dalam file teks dalam format seperti CSV agar mudah dibaca. Caranya, program membuka file dengan ofstream, menulis header kolom, lalu mencatat data dari daftar produk yang tersedia. Setelah selesai, file ditutup untuk memastikan data tersimpan. Format ekspor juga bisa disesuaikan, misalnya dengan menambahkan tanggal pada nama file agar lebih terorganisir.

**Comment by Rizki-Andaru** [comment]
> ## Pertanyaan Review
> 1. Pada fungsi `ubahHarga()`, jelaskan mengapa tidak ada validasi untuk harga baru yang dimasukkan?
> 2. Bagaimana jika user memasukkan input berupa huruf saat diminta memasukkan angka (misalnya saat input jumlah stok)?
> 3. Program belum memiliki fungsi untuk mencari produk. Bagaimana implementasi fungsi pencarian produk berdasarkan nama?
> 4. Bagaimana jika ingin menambahkan fitur untuk mengekspor laporan penjualan ke format teks tertentu?
> 
> ## Cara Menjawab
> 1. Reply pada thread issue GitHub ini
> 2. Jelaskan setiap poin pertanyaan
> 3. Sebutkan file yang dimodifikasi/ditambahkan
> 4. Sertakan kode yang berubah/ditambahkan
